# Generated by Django 3.2.9 on 2021-11-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='recipient_id',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
